### ISSUE TITLE
[Content/link] Add link to ersei.net

### ISSUE THREAD

**Issue by 9p4** [photogabble/hyperlink-cafe#10]
### Site Title

Ersei 'n Stuff

### Site Links Page URL

https://ersei.net/en/blogroll

### Site Source URL

https://git.sr.ht/~fd/ersei.net

### Website description

Hi! I'm Ersei! I am a sophomore at Purdue University studying (can you believe it) computer science. Well, it appears that I have a website now. I wonder what I can do with it?

**Comment by carbontwelve** [comment]
@9p4 thank you for your interest in this project :)
