### ISSUE TITLE
[Content/link] Add link to blog.darylsun.page

### ISSUE THREAD

**Issue by DarylSum** [photogabble/hyperlink-cafe#7]
### Site Title

Daryl Sun's Journal

### Site Links Page URL

https://blog.darylsun.page/blogroll

### Site Source URL

https://git.sr.ht/~darylsun/blog

### Website description

An online diary of a lady's misadventures in two worlds

**Comment by carbontwelve** [comment]
Thankyou for your interest in the project :D
